// ならべるクイズ問題  stars:1=★(2-3文字) 2=★★(4文字) 3=★★★(5文字以上)
// audio フィールドがある場合はTTS用テキストとして使用（yomiと読みが異なる場合）
const NARABE = [
  // ===== ★ (2文字) =====
  { img:'kumo.svg',                  yomi:'くも',             stars:1 },
  { img:'zou.svg',                   yomi:'ぞう',             stars:1 },
  { img:'ame-ga-furu.svg',           yomi:'あめ',             stars:1 },
  { img:'yuki-ga-furu.svg',          yomi:'ゆき',             stars:1 },
  { img:'hoshi-kirakira.svg',        yomi:'ほし',             stars:1 },
  { img:'hana-ga-saku.svg',          yomi:'はな',             stars:1 },
  { img:'inu-ga-aruku.svg',          yomi:'いぬ',             stars:1 },
  // ===== ★ (3文字) =====
  { img:'nezumi.svg',                yomi:'ねずみ',           stars:1 },
  { img:'usagi-jump.svg',            yomi:'うさぎ',           stars:1 },
  { img:'udon.svg',                  yomi:'うどん',           stars:1 },
  { img:'birthday-cake.svg',         yomi:'けーき',           stars:1 },
  { img:'hanabi-uchiage.svg',        yomi:'はなび',           stars:1 },
  { img:'sakura-saku.svg',           yomi:'さくら',           stars:1 },
  { img:'momiji-chiru.svg',          yomi:'もみじ',           stars:1 },
  // ===== ★★ (4文字) =====
  { img:'ra-men.svg',                yomi:'らーめん',         stars:2 },
  { img:'taiyou-kagayaki.svg',       yomi:'たいよう',         stars:2 },
  { img:'kaminari-ga-naru.svg',      yomi:'かみなり',         stars:2 },
  { img:'ame-gumo.svg',              yomi:'あまぐも',         stars:2 },
  { img:'te-wo-fuku.svg',            yomi:'てをふく',         stars:2 },
  { img:'patokaa-ga-hashiru.svg',    yomi:'ぱとかー',         stars:2 },
  { img:'ureshii-kao.svg',           yomi:'うれしい',         stars:2 },
  { img:'kanashii-kao.svg',          yomi:'かなしい',         stars:2 },
  { img:'ookii-booru.svg',           yomi:'おおきい',         stars:2 },
  { img:'chiisai-booru.svg',         yomi:'ちいさい',         stars:2 },
  { img:'nagai-densha-ga-hashiru.svg',yomi:'でんしゃ',        stars:2 },
  // ===== ★★★ (5文字以上・フレーズ) =====
  { img:'natsu-no-umi.svg',          yomi:'なつのうみ',       stars:3 },
  { img:'kaminari-ga-naru.svg',       yomi:'かみなりがなる',   stars:3 },
  { img:'te-wo-arau.svg',            yomi:'てをあらう',       stars:3 },
  { img:'ha-wo-migaku.svg',          yomi:'はをみがく', audio:'歯をみがく', stars:3 },
  { img:'inu-ga-aruku.svg',          yomi:'いぬがあるく',     stars:3 },
  { img:'inu-ga-hashiru.svg',        yomi:'いぬがはしる',     stars:3 },
  { img:'kaidan-wo-noboru.svg',      yomi:'かいだんをのぼる', stars:3 },
  { img:'ie-ni-kaeru.svg',           yomi:'いえにかえる',     stars:3 },
  { img:'tsumetai-mizu.svg',         yomi:'つめたいみず',     stars:3 },
  { img:'atsui-oyu.svg',             yomi:'あついおゆ',       stars:3 },
  { img:'sakura-chiru.svg',          yomi:'さくらがちる',     stars:3 },
  { img:'nagai-densha-ga-hashiru.svg',yomi:'ながいでんしゃ',  stars:3 },
  { img:'denki-wo-tsukeru.svg',      yomi:'でんきをつける',   stars:3 },
  { img:'kaidan-wo-oriru.svg',       yomi:'かいだんをおりる', stars:3 },
  { img:'ureshii-kao.svg',           yomi:'うれしいかお',     stars:3 },
  { img:'kanashii-kao.svg',          yomi:'かなしいかお',     stars:3 },
  // ===== 新規追加 =====
  // ★ (2-3文字)
  { img:'neko.svg',                  yomi:'ねこ',             stars:1 },
  { img:'kingyo.svg',                yomi:'きんぎょ',         stars:1 },
  { img:'warau-kao.svg',             yomi:'わらう',           stars:1 },
  // ★★ (4文字)
  { img:'hikouki-ga-tobu.svg',       yomi:'ひこうき',         stars:2 },
  { img:'soujiki-de-souji.svg',      yomi:'そうじき',         stars:2 },
  { img:'naku-kao.svg',              yomi:'なきがお',         stars:2 },
  { img:'hanbaagu-wo-kiru.svg',      yomi:'はんばーぐ',       stars:2 },
  // ★★★ (フレーズ)
  { img:'tori-ga-tobu.svg',          yomi:'とりがとぶ',       stars:3 },
  { img:'mado-wo-akeru.svg',         yomi:'まどをあける',     stars:3 },
  { img:'mado-wo-shimeru.svg',       yomi:'まどをしめる',     stars:3 },
  { img:'warau-kao.svg',             yomi:'わらったかお',     stars:3 },
  { img:'hikouki-ga-tobu.svg',       yomi:'ひこうきがとぶ',   stars:3 },
  { img:'hanbaagu-wo-kiru.svg',      yomi:'はんばーぐをきる', stars:3 },
  // ===== 新規追加2 =====
  // ★ (3文字)
  { img:'piano-playing.svg',         yomi:'ぴあの',           stars:1 },
  { img:'crossing-crosswalk-safe.svg',yomi:'わたる',          stars:1 },
  // ★★ (4文字)
  { img:'crayon-drawing-circle.svg', yomi:'くれよん',         stars:2 },
  { img:'pencil-drawing-square.svg', yomi:'えんぴつ',         stars:2 },
  // ★★★ (フレーズ)
  { img:'playing-tambourine.svg',    yomi:'たんばりん',       stars:3 },
  { img:'piano-playing.svg',         yomi:'ぴあのをひく',     stars:3 },
  { img:'boarding-train.svg',        yomi:'でんしゃにのる',   stars:3 },
  { img:'densha-wo-oriru.svg',       yomi:'でんしゃをおりる', stars:3 },
  { img:'crayon-drawing-circle.svg', yomi:'くれよんでかく',   stars:3 },
  { img:'pencil-drawing-square.svg', yomi:'えんぴつでかく',   stars:3 },
  { img:'crossing-crosswalk-safe.svg',yomi:'しんごうをわたる', stars:3 },
  { img:'waiting-crosswalk-cars.svg', yomi:'しんごうをまつ',   stars:3 },
  // ===== 新規追加3 =====
  { img:'rolling_sushi.svg',          yomi:'すし',             stars:1 },
  { img:'orange_juice_nomu.svg',      yomi:'じゅーす',         stars:2 },
  { img:'rolling_sushi.svg',          yomi:'かいてんずし',     stars:3 },
  { img:'orange_juice_nomu.svg',      yomi:'じゅーすをのむ',   stars:3 },
];

// えらぶクイズ問題  correct:1=img1が正解 / 2=img2が正解
const ERABE = [
  { img1:'inu-ga-aruku.svg',             img2:'usagi-jump.svg',              audio:'いぬが あるくのは どっち？',     correct:1 },
  { img1:'denki-wo-tsukeru.svg',         img2:'denki-wo-kesu.svg',           audio:'でんきを つけるのは どっち？',   correct:1 },
  { img1:'terebi-wo-tsukeru.svg',        img2:'terebi-wo-kesu.svg',          audio:'てれびを つけるのは どっち？',   correct:1 },
  { img1:'doa-wo-akeru.svg',             img2:'doa-wo-shimeru.svg',          audio:'ドアを あけるのは どっち？',     correct:1 },
  { img1:'kasa-wo-akeru.svg',            img2:'kasa-wo-shimeru.svg',         audio:'かさを ひらくのは どっち？',     correct:1 },
  { img1:'chiisai-booru.svg',            img2:'ookii-booru.svg',             audio:'おおきい ボールは どっち？',     correct:2 },
  { img1:'ureshii-kao.svg',              img2:'kanashii-kao.svg',            audio:'うれしいのは どっち？',          correct:1 },
  { img1:'sakura-saku.svg',              img2:'sakura-chiru.svg',            audio:'さくらが さくのは どっち？',     correct:1 },
  { img1:'kaidan-wo-noboru.svg',         img2:'kaidan-wo-oriru.svg',         audio:'かいだんを のぼるのは どっち？', correct:1 },
  { img1:'ame-ga-furu.svg',              img2:'yuki-ga-furu.svg',            audio:'ゆきが ふるのは どっち？',       correct:2 },
  { img1:'mijikai-densha-ga-hashiru.svg',img2:'nagai-densha-ga-hashiru.svg', audio:'ながい でんしゃは どっち？',     correct:2 },
  { img1:'ra-men.svg',                   img2:'udon.svg',                    audio:'らーめんは どっち？',             correct:1 },
  { img1:'zou.svg',                      img2:'nezumi.svg',                  audio:'ぞうは どっち？',                 correct:1 },
  { img1:'kyuukyuusha-ga-tomaru.svg',    img2:'patokaa-ga-hashiru.svg',      audio:'きゅうきゅうしゃは どっち？',     correct:1 },
  { img1:'atsui-oyu.svg',                img2:'tsumetai-mizu.svg',           audio:'あついのは どっち？',             correct:1 },
  { img1:'te-wo-arau.svg',               img2:'te-wo-fuku.svg',              audio:'てを あらうのは どっち？',       correct:1 },
  { img1:'hana-ga-saku.svg',             img2:'momiji-chiru.svg',            audio:'はなが さくのは どっち？',       correct:1 },
  { img1:'sora-ga-hareru.svg',           img2:'ame-gumo.svg',                audio:'そらが晴れるのは どっち？', text:'そらがはれるのは どっち？', correct:1 },
  { img1:'taiyou-kagayaki.svg',          img2:'kaminari-ga-naru.svg',        audio:'たいようは どっち？',             correct:1 },
  { img1:'ie-ni-kaeru.svg',              img2:'ha-wo-migaku.svg',            audio:'いえに かえるのは どっち？',     correct:1 },
  { img1:'birthday-cake.svg',            img2:'ra-men.svg',                  audio:'ケーキは どっち？',               correct:1 },
  { img1:'usagi-jump.svg',               img2:'zou-jump.svg',                audio:'うさぎは どっち？',               correct:1 },
  { img1:'hanabi-uchiage.svg',           img2:'hoshi-kirakira.svg',          audio:'花火は どっち？', text:'はなびは どっち？', correct:1 },
  { img1:'natsu-no-umi.svg',             img2:'yuki-ga-furu.svg',            audio:'なつは どっち？',                 correct:1 },
  { img1:'kaidan-wo-noboru.svg',         img2:'ie-ni-kaeru.svg',             audio:'いえに かえるのは どっち？',     correct:2 },
  { img1:'zou-jump.svg',                  img2:'usagi-jump.svg',              audio:'おもいのはどっち？',              correct:1 },
  // ===== 新規追加 =====
  { img1:'mado-wo-akeru.svg',            img2:'mado-wo-shimeru.svg',         audio:'まどを あけるのは どっち？',     correct:1 },
  { img1:'warau-kao.svg',                img2:'naku-kao.svg',                audio:'わらっているのは どっち？',       correct:1 },
  { img1:'neko.svg',                     img2:'kingyo.svg',                  audio:'ねこは どっち？',                 correct:1 },
  { img1:'tori-ga-tobu.svg',             img2:'hikouki-ga-tobu.svg',         audio:'とりは どっち？',                 correct:1 },
  { img1:'soujiki-de-souji.svg',         img2:'te-wo-arau.svg',              audio:'そうじきは どっち？',             correct:1 },
  { img1:'neko.svg',                     img2:'inu-ga-aruku.svg',            audio:'いぬは どっち？',                 correct:2 },
  { img1:'usagi-jump.svg',               img2:'zou-jump.svg',                audio:'かるいのはどっち？',              correct:1 },
  { img1:'ha-wo-migaku.svg',             img2:'ureshii-kao.svg',             audio:'歯をみがくのは どっち？', text:'はをみがくのは どっち？', correct:1 },
  { img1:'kingyo.svg',                   img2:'inu-ga-hashiru.svg',          audio:'およぐのは どっち？',               correct:1 },
  { img1:'yuki-ga-furu.svg',             img2:'natsu-no-umi.svg',            audio:'ふゆは どっち？',                   correct:1 },
  { img1:'sakura-saku.svg',              img2:'icho-namiki.svg',             audio:'はるは どっち？',                   correct:1 },
  { img1:'okiru.svg',                    img2:'neru.svg',                    audio:'おきたのは どっち？',               correct:1 },
  { img1:'neru.svg',                     img2:'okiru.svg',                   audio:'ねているのは どっち？',             correct:1 },
  { img1:'mado-wo-shimeru.svg',          img2:'mado-wo-akeru.svg',           audio:'まどをしめるのは どっち？',         correct:1 },
  // ===== 新規追加2 =====
  { img1:'boarding-train.svg',           img2:'densha-wo-oriru.svg',         audio:'でんしゃに のるのは どっち？',       correct:1 },
  { img1:'densha-wo-oriru.svg',          img2:'boarding-train.svg',          audio:'でんしゃを おりるのは どっち？',     correct:1 },
  { img1:'crossing-crosswalk-safe.svg',  img2:'waiting-crosswalk-cars.svg',  audio:'あおしんごうはどっち？',            correct:1 },
  { img1:'piano-playing.svg',            img2:'playing-tambourine.svg',      audio:'ぴあのを ひくのは どっち？',         correct:1 },
  { img1:'playing-tambourine.svg',       img2:'piano-playing.svg',           audio:'タンバリンをたたくのは どっち？',   correct:1 },
  { img1:'crayon-drawing-circle.svg',    img2:'pencil-drawing-square.svg',   audio:'クレヨンは どっち？',               correct:1 },
  { img1:'pencil-drawing-square.svg',    img2:'crayon-drawing-circle.svg',   audio:'鉛筆は どっち？', text:'えんぴつは どっち？', correct:1 },
  { img1:'waiting-crosswalk-cars.svg',   img2:'crossing-crosswalk-safe.svg', audio:'まつのは どっち？',                 correct:1 },
  { img1:'crayon-drawing-circle.svg',    img2:'pencil-drawing-square.svg',   audio:'せんがふといのは どっち？',         correct:1 },
  { img1:'pencil-drawing-square.svg',    img2:'crayon-drawing-circle.svg',   audio:'せんがほそいのは どっち？',         correct:1 },
  { img1:'pencil-drawing-square.svg',    img2:'crayon-drawing-circle.svg',   audio:'しかくは どっち？',                 correct:1 },
  { img1:'crayon-drawing-circle.svg',    img2:'pencil-drawing-square.svg',   audio:'まるは どっち？',                   correct:1 },
  // ===== 新規追加3 =====
  { img1:'chiisai-booru.svg',            img2:'ookii-booru.svg',             audio:'ボールがおおきいのは どっち？',      correct:2 },
  // ===== 新規追加4 =====
  { img1:'waiting-crosswalk-cars.svg',   img2:'crossing-crosswalk-safe.svg', audio:'あかしんごうは どっち？',            correct:1 },
  { img1:'te-wo-fuku.svg',               img2:'te-wo-arau.svg',              audio:'てを ふくのは どっち？',             correct:1 },
  // ===== 新規追加5 =====
  { img1:'yuki-ga-furu.svg',             img2:'ame-ga-furu.svg',              audio:'あめが ふるのは どっち？',             correct:2 },
  { img1:'orange_juice_nomu.svg',        img2:'hanbaagu-wo-kiru.svg',         audio:'ジュースをのむのは どっち？',          correct:1 },
  { img1:'hanbaagu-wo-kiru.svg',         img2:'orange_juice_nomu.svg',        audio:'ハンバーグをたべるのは どっち？',      correct:1 },
  { img1:'rolling_sushi.svg',            img2:'hanbaagu-wo-kiru.svg',         audio:'おすしは どっち？',                   correct:1 },
];
